export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const BOOKS_LOADED_SUCCESFULLY = 'BOOKS_LOADED_SUCCESFULLY';
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const BOOK_FETCHED_SUCCESFULLY = 'BOOK_FETCHED_SUCCESFULLY';